### ISSUE TITLE
verifying proof on blockchain

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [akosba/jsnark#16]
Hi.Can a prover put her proof that has created using jsnark on blockchain and is there any smart contract auto created by jsnark that can verify these proofs?I mean something like what [Zokrates](https://github.com/Zokrates/ZoKrates) does.

**Comment by HarryR** [comment]
There is an example created by appliedblockchain which uses jsnark in combination with ethsnarks: https://github.com/appliedblockchain/jsnark-ethsnarks-examples

This relies on exporting your jsnark or xjsnark circuit to the extended pinocchio opcode format, which can then be interpreted by ethsnarks.

However, there are some incompatibilities with ethsnarks which means it can't handle all of the opcodes correctly.

**Comment by akosba** [comment]
> Hi.Can a prover put her proof that has created using jsnark on blockchain and is there any smart contract auto created by jsnark that can verify these proofs?I mean something like what [Zokrates](https://github.com/Zokrates/ZoKrates) does.

As HarryR suggested, you might want to look into other tools that can help with the integration. Auto creation of smart contracts is not supported by the current version.
