### ISSUE TITLE
Change the curve

### ISSUE THREAD

**Issue by SilverPoker** [akosba/jsnark#21]
Hi akosba,
Is it still correct if I implement another curve in libsnark and use the same .arith and .in file directly as my input? I tried using the MNT4753 for libsnark which is a 768bit-curve but the constraint system doesn't satisfy itself. (assertion in CircuitReader.cpp, some assigned value changes because the field changes) I wonder whether this library can only use a 254-bit curve as its backend now?

But the way I used the implementation from coda, I think the curve has the same api as other curves in libsnark.
https://github.com/CodaProtocol/gpu-groth16-prover-3x

**Comment by akosba** [comment]
You will need to update the [configuration file](https://github.com/akosba/jsnark/blob/master/JsnarkCircuitBuilder/config.properties) in jsnark accordingly.

**Comment by SilverPoker** [comment]
It works, thank you very much! I have been looking for the bug for several days...
